apiVersion: v1
kind: Pod
metadata:
  name: app-web-mysql
  labels:
    name: app-web-mysql
spec:
  containers:
  - name: app-web-mysql
    image: kodekloud/app-web-mysql:1.0
    ports:
    - containerPort: 9080
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
