apiVersion: v1
kind: Pod
metadata:
  name: app-web-mysql
  labels:
    name: app-web-mysql
spec:
  containers:
  - name: app-web-mysql
    image: ghcr.io/wiktorvip/app-web-mysql:v1
    ports:
    - containerPort: 9070
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
