apiVersion: v1
kind: Pod
metadata:
  name: app-web-mysql
  labels:
    name: app-web-mysql
spec:
  containers:
  - name: app-web-mysql
    image: ghcr.io/wiktorvip/app-web-mysql:v1
    ports:
    - containerPort: 9080
